apiVersion: v2
name: liqo-upgrade-operator
description: Kubernetes operator for managing Liqo version upgrades
type: application
version: 0.1.0
appVersion: "0.1"
keywords:
  - liqo
  - upgrade
  - operator
  - kubernetes
maintainers:
  - name: Kazem

