apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liqo-upgrade-operator.fullname" . }}-manager
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "liqo-upgrade-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "liqo-upgrade-operator.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "liqo-upgrade-operator.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.podSecurityContext.runAsNonRoot }}
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /manager
        args:
        {{- if .Values.metrics.enabled }}
        - --metrics-bind-address=:{{ .Values.metrics.port }}
        {{- end }}
        {{- if .Values.leaderElection.enabled }}
        - --leader-elect
        {{- end }}
        - --health-probe-bind-address=:{{ .Values.healthProbe.port }}
        ports:
        {{- if .Values.metrics.enabled }}
        - containerPort: {{ .Values.metrics.port }}
          name: https
          protocol: TCP
        {{- end }}
        securityContext:
          readOnlyRootFilesystem: {{ .Values.containerSecurityContext.readOnlyRootFilesystem }}
          allowPrivilegeEscalation: {{ .Values.containerSecurityContext.allowPrivilegeEscalation }}
          capabilities:
            drop:
            {{- range .Values.containerSecurityContext.capabilities.drop }}
            - {{ . | quote }}
            {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.healthProbe.port }}
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.healthProbe.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      serviceAccountName: {{ include "liqo-upgrade-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10

