apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "liqo-upgrade-operator.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "liqo-upgrade-operator.labels" . | nindent 4 }}

